"""AI-generated summary and its repeating sections."""

from __future__ import annotations

from datetime import datetime
from typing import TYPE_CHECKING

from sqlalchemy import (
    Boolean,
    DateTime,
    ForeignKey,
    Integer,
    String,
    Text,
    func,
)
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base, TimestampMixin
from app.models.enums import SummarySectionKind, enum_column

if TYPE_CHECKING:
    from app.models.meeting import Meeting


class Summary(Base, TimestampMixin):
    """One summary per meeting.

    Holds the SCALAR parts — a single overview paragraph, a one-line gist, and
    provenance. The repeating parts (outline chapters, grouped bullet notes) are
    rows in `summary_sections`; keywords and action items have their own tables.

    PLAN.md additionally proposed a `bullet_notes JSON` column here, which is
    dropped: a JSON blob cannot be ordered, queried or partially updated, and it
    duplicated what `summary_sections` already models. See docs/schema.md.
    """

    __tablename__ = "summaries"

    id: Mapped[int] = mapped_column(primary_key=True)
    #: UNIQUE, not just a foreign key — one summary per meeting is an invariant,
    #: and regeneration replaces the row's contents rather than adding a second.
    meeting_id: Mapped[int] = mapped_column(
        ForeignKey("meetings.id", ondelete="CASCADE"),
        nullable=False,
        unique=True,
        index=True,
    )

    overview: Mapped[str | None] = mapped_column(Text, nullable=True)
    gist: Mapped[str | None] = mapped_column(String(400), nullable=True)

    #: Provenance, surfaced in the UI's "Generated by X" attribution row
    #: (T-23.10). Stored because the honest answer differs per meeting — a
    #: fallback to the mock provider after an LLM timeout must be visible.
    provider: Mapped[str] = mapped_column(String(60), nullable=False, default="mock")
    model: Mapped[str | None] = mapped_column(String(120), nullable=True)

    generated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )

    #: Set when the transcript is edited after generation (T-17.5), which drives
    #: the amber "Outdated" badge. A boolean rather than a timestamp comparison
    #: because the trigger is an explicit event, not a clock race.
    is_stale: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)

    meeting: Mapped[Meeting] = relationship(back_populates="summary")
    sections: Mapped[list[SummarySection]] = relationship(
        back_populates="summary",
        cascade="all, delete-orphan",
        lazy="selectin",
        order_by="SummarySection.sequence",
    )

    def __repr__(self) -> str:
        return f"<Summary m={self.meeting_id} provider={self.provider}>"


class SummarySection(Base):
    """A repeating piece of a summary: an outline chapter or a note group.

    `start_ms` is what makes the Meeting Outline clickable — each chapter maps
    to a real moment, so the timestamp can seek the player and scroll the
    transcript (T-21.6). Note rows carry a null `start_ms` and are grouped under
    their chapter by `title`.
    """

    __tablename__ = "summary_sections"

    id: Mapped[int] = mapped_column(primary_key=True)
    summary_id: Mapped[int] = mapped_column(
        ForeignKey("summaries.id", ondelete="CASCADE"), nullable=False, index=True
    )

    kind: Mapped[SummarySectionKind] = mapped_column(
        enum_column(SummarySectionKind, "summary_section_kind"),
        nullable=False,
    )

    title: Mapped[str | None] = mapped_column(String(300), nullable=True)
    body: Mapped[str | None] = mapped_column(Text, nullable=True)

    #: Outline entries only. Must land inside a real segment's range — asserted
    #: by the seed validator (T-05.14) rather than by a constraint, since SQLite
    #: cannot express a cross-table CHECK.
    start_ms: Mapped[int | None] = mapped_column(Integer, nullable=True)

    sequence: Mapped[int] = mapped_column(Integer, nullable=False, default=0)

    summary: Mapped[Summary] = relationship(back_populates="sections")

    def __repr__(self) -> str:
        return f"<SummarySection {self.kind} #{self.sequence} {self.title!r}>"
