/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/health': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Service health
     * @description Reports liveness, database reachability and the active configuration. Returns **503** when the database cannot be reached, so a host's health check takes the instance out of rotation rather than serving errors.
     */
    get: operations['health_api_health_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/channels': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List channels with counts
     * @description Channels plus the two built-in views. Counts exclude deleted meetings, and a channel with no meetings still appears, showing zero.
     */
    get: operations['list_channels_api_v1_channels_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/me': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Current user
     * @description Authentication is out of scope for this build: this returns the seeded default user. It is a dependency rather than a constant, so swapping in real auth changes one function and no route signatures.
     */
    get: operations['read_me_api_v1_me_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/meetings': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List meetings
     * @description Paginated, newest first. Returns the LIGHT row shape — no transcript and no full summary; use `GET /meetings/{id}` for detail.
     *
     *     `from` and `to` are inclusive dates in UTC: `to=2026-07-26` includes everything that happened ON the 26th.
     *
     *     `q` matches the title, the overview, participant names and the transcript. When the hit came from the transcript — and only then — the row carries `match_context` explaining why.
     */
    get: operations['list_meetings_api_v1_meetings_get']
    put?: never
    /**
     * Create a meeting
     * @description Creates an empty meeting. Transcript ingestion happens separately.
     */
    post: operations['create_meeting_api_v1_meetings_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/meetings/bulk-delete': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Delete several meetings
     * @description Reports per-id failures rather than aborting the batch, so the client can say '2 of 3 deleted' instead of leaving the user guessing.
     */
    post: operations['bulk_delete_api_v1_meetings_bulk_delete_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/meetings/facets': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Available filter values
     * @description Distinct hosts, participants, tags and channels across non-deleted meetings, plus the duration bounds. Derived from real data so the filter panel can never offer an option that matches nothing.
     */
    get: operations['meeting_facets_api_v1_meetings_facets_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/meetings/{meeting_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get a meeting
     * @description 404 if the meeting never existed; **410** if it was deleted, since a deleted meeting is restorable and the client can offer that.
     */
    get: operations['get_meeting_api_v1_meetings__meeting_id__get']
    put?: never
    post?: never
    /**
     * Delete a meeting
     * @description Soft delete. The meeting disappears from lists but is restorable.
     */
    delete: operations['delete_meeting_api_v1_meetings__meeting_id__delete']
    options?: never
    head?: never
    /**
     * Update a meeting
     * @description Partial update — omitted fields are left untouched.
     */
    patch: operations['update_meeting_api_v1_meetings__meeting_id__patch']
    trace?: never
  }
  '/api/v1/meetings/{meeting_id}/restore': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Restore a deleted meeting
     * @description Undoes a soft delete. Backs the 6-second Undo affordance in the UI.
     */
    post: operations['restore_meeting_api_v1_meetings__meeting_id__restore_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/meetings/{meeting_id}/summary/regenerate': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Regenerate a meeting summary
     * @description Rate limited to 10 requests per minute — this is the endpoint that calls a model, and an accidental double-click should not double the bill.
     */
    post: operations['regenerate_summary_api_v1_meetings__meeting_id__summary_regenerate_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/search': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Search meetings and transcripts
     * @description FTS5-ranked, grouped into title matches and transcript matches. Snippets carry match RANGES rather than markup — the client wraps them, so transcript text containing HTML is rendered rather than executed. Queries shorter than two characters return nothing.
     */
    get: operations['search_api_v1_search_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /**
     * ActionItemCounts
     * @description Pre-aggregated so the row does not have to count client-side.
     */
    ActionItemCounts: {
      /**
       * Completed
       * @default 0
       */
      completed: number
      /**
       * Open
       * @default 0
       */
      open: number
    }
    /** BulkDeleteRequest */
    BulkDeleteRequest: {
      /** Ids */
      ids: number[]
    }
    /** BulkDeleteResponse */
    BulkDeleteResponse: {
      /** Deleted */
      deleted: number
      /**
       * Failed
       * @description Ids that could not be deleted, e.g. already gone.
       */
      failed?: number[]
    }
    /**
     * ChannelOut
     * @description A sidebar channel, with its meeting count.
     *
     *     The count is what makes the rail feel alive rather than decorative, and it
     *     is aggregated server-side — the alternative is the client fetching every
     *     meeting just to group them.
     */
    ChannelOut: {
      /** Icon */
      icon?: string | null
      /** Id */
      id: number
      /** Is Private */
      is_private: boolean
      /**
       * Meeting Count
       * @description Meetings in this channel, excluding deleted.
       */
      meeting_count: number
      /** Name */
      name: string
      /** Slug */
      slug: string
    }
    /** ErrorDetail */
    ErrorDetail: {
      /**
       * Code
       * @description Stable machine-readable identifier; safe to branch on.
       */
      code: string
      /**
       * Details
       * @description Field-level errors, keyed by dotted path, when applicable.
       */
      details?: {
        [key: string]: unknown
      }
      /**
       * Message
       * @description Human-readable explanation. Wording may change.
       */
      message: string
    }
    /**
     * ErrorResponse
     * @description Every non-2xx response body in the API has this shape.
     *
     *     Nested under a single `error` key rather than flattened, so a client can
     *     tell an error from a successful payload without inspecting the status code —
     *     which matters for the fetch wrapper in T-06.4.
     */
    ErrorResponse: {
      error: components['schemas']['ErrorDetail']
    }
    /**
     * Facets
     * @description Available filter values, derived from real data (T-11.8).
     *
     *     Sent so the filter panel can never offer an option that matches nothing,
     *     which is how a filter panel loses the user's trust on the first click.
     */
    Facets: {
      /** Channels */
      channels: string[]
      /** Hosts */
      hosts: string[]
      /** Max Duration */
      max_duration: number
      /** Min Duration */
      min_duration: number
      /** Participants */
      participants: string[]
      /** Tags */
      tags: string[]
    }
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][]
    }
    /** HealthResponse */
    HealthResponse: {
      /**
       * Ai Provider
       * @description Active summary/extraction provider.
       */
      ai_provider: string
      /**
       * Db
       * @description Result of a real SELECT 1.
       * @enum {string}
       */
      db: 'up' | 'down'
      /**
       * Status
       * @description Overall service state.
       * @enum {string}
       */
      status: 'ok' | 'degraded'
      /**
       * Version
       * @description Deployed application version.
       */
      version: string
    }
    /**
     * MatchContext
     * @description Why a meeting matched, when the reason is not visible in the row (T-11.3).
     *
     *     Present ONLY when the hit came from the transcript. A title match needs no
     *     explanation — the user can read it — but a transcript match looks like a
     *     false positive unless the row shows the line that caused it.
     */
    MatchContext: {
      /** Snippet */
      snippet: string
      /** Speaker */
      speaker: string
      /** Start Ms */
      start_ms: number
    }
    /**
     * MatchRange
     * @description Character offsets of a matched term within a snippet.
     */
    MatchRange: {
      /** End */
      end: number
      /** Start */
      start: number
    }
    /**
     * MediaType
     * @enum {string}
     */
    MediaType: 'audio' | 'video' | 'none'
    /**
     * MeetingCreate
     * @description Creating a meeting from the form, a paste, or an upload.
     */
    MeetingCreate: {
      /** Channel Id */
      channel_id?: number | null
      /** Description */
      description?: string | null
      /**
       * Language
       * @default en
       */
      language: string
      /** Participant Names */
      participant_names?: string[]
      /** @default manual */
      source: components['schemas']['MeetingSource']
      /**
       * Started At
       * @description Defaults to now when omitted.
       */
      started_at?: string | null
      /** Title */
      title: string
      /** @default private */
      visibility: components['schemas']['Visibility']
    }
    /**
     * MeetingDetail
     * @description The Notepad payload. Heavy, and only ever returned for a single meeting.
     *
     *     Transcript segments are NOT here — they are paginated separately via
     *     `/meetings/{id}/transcript` (T-17.2), because a 55-minute meeting is ~1,200
     *     segments and shipping them inline makes the first paint wait on all of them.
     */
    MeetingDetail: {
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
      /** Description */
      description?: string | null
      /** Duration Seconds */
      duration_seconds: number
      host: components['schemas']['UserRef']
      /** Id */
      id: number
      /** Keywords */
      keywords?: string[]
      /** Language */
      language: string
      media_type: components['schemas']['MediaType']
      /** Media Url */
      media_url?: string | null
      /** Participants */
      participants?: components['schemas']['ParticipantRef'][]
      processing_status: components['schemas']['ProcessingStatus']
      /**
       * Segment Count
       * @default 0
       */
      segment_count: number
      source: components['schemas']['MeetingSource']
      /**
       * Started At
       * Format: date-time
       */
      started_at: string
      /** Tags */
      tags?: components['schemas']['TagRef'][]
      /** Title */
      title: string
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string
      visibility: components['schemas']['Visibility']
    }
    /**
     * MeetingHit
     * @description A meeting whose title or overview matched.
     */
    MeetingHit: {
      /** Duration Seconds */
      duration_seconds: number
      /** Id */
      id: number
      /** Matches */
      matches: components['schemas']['MatchRange'][]
      /** Started At */
      started_at: string
      /** Title */
      title: string
    }
    /**
     * MeetingListItem
     * @description One row of the Notebook. LIGHT — no transcript, no full summary.
     *
     *     Carries a one-line `overview_preview` rather than the whole overview, since
     *     the row clamps it to a single line anyway.
     */
    MeetingListItem: {
      action_item_counts: components['schemas']['ActionItemCounts']
      /** Duration Seconds */
      duration_seconds: number
      /**
       * Has Media
       * @default false
       */
      has_media: boolean
      host: components['schemas']['UserRef']
      /** Id */
      id: number
      /** Keywords */
      keywords?: string[]
      match_context?: components['schemas']['MatchContext'] | null
      /** @default none */
      media_type: components['schemas']['MediaType']
      /** Overview Preview */
      overview_preview?: string | null
      /**
       * Participant Count
       * @default 0
       */
      participant_count: number
      /**
       * Participants
       * @description Capped; `participant_count` has the true total.
       */
      participants?: components['schemas']['ParticipantRef'][]
      /**
       * Started At
       * Format: date-time
       */
      started_at: string
      /** Tags */
      tags?: components['schemas']['TagRef'][]
      /** Title */
      title: string
    }
    /**
     * MeetingSource
     * @enum {string}
     */
    MeetingSource: 'upload' | 'manual' | 'seed' | 'integration'
    /**
     * MeetingUpdate
     * @description Partial update. Every field optional; unset fields are left alone.
     */
    MeetingUpdate: {
      /** Channel Id */
      channel_id?: number | null
      /** Description */
      description?: string | null
      /** Language */
      language?: string | null
      /** Started At */
      started_at?: string | null
      /** Title */
      title?: string | null
      visibility?: components['schemas']['Visibility'] | null
    }
    /**
     * NoteGroup
     * @description Bullet notes, grouped under their outline chapter.
     */
    NoteGroup: {
      /** Bullets */
      bullets?: string[]
      /** Chapter */
      chapter?: string | null
    }
    /**
     * OutlineEntry
     * @description One chapter of the Meeting Outline.
     */
    OutlineEntry: {
      /**
       * Sequence
       * @default 0
       */
      sequence: number
      /** Start Ms */
      start_ms: number
      /** Title */
      title: string
    }
    /** Page[MeetingListItem] */
    Page_MeetingListItem_: {
      /** Has Next */
      readonly has_next: boolean
      /** Items */
      items: components['schemas']['MeetingListItem'][]
      /**
       * Page
       * @description 1-indexed page number.
       */
      page: number
      /** Page Size */
      page_size: number
      /**
       * Total
       * @description Total matching rows, ignoring pagination.
       */
      total: number
      /** Total Pages */
      readonly total_pages: number
    }
    /**
     * ParticipantRef
     * @description Enough to render an avatar in a group.
     */
    ParticipantRef: {
      /** Avatar Url */
      avatar_url?: string | null
      /** Display Name */
      display_name: string
      /** Id */
      id: number
    }
    /**
     * ProcessingStatus
     * @enum {string}
     */
    ProcessingStatus: 'pending' | 'processing' | 'ready' | 'failed'
    /**
     * SearchResults
     * @description Grouped, because the two kinds of hit mean different things.
     *
     *     A title match is "this meeting is about X"; a transcript match is "X was
     *     said at 18:42". Flattening them loses that distinction and makes the
     *     dropdown harder to scan.
     */
    SearchResults: {
      /** Meetings */
      meetings: components['schemas']['MeetingHit'][]
      /** Query */
      query: string
      /**
       * Total
       * @description Combined count across both groups.
       */
      total: number
      /** Transcripts */
      transcripts: components['schemas']['TranscriptHit'][]
    }
    /**
     * SidebarChannels
     * @description Everything the rail's CHANNELS section needs, in one request.
     *
     *     The two built-in views are counts rather than channel rows — "My Meetings"
     *     and "All Meetings" are filters over the same data, not stored channels —
     *     so returning them alongside avoids the client making three calls to render
     *     one list.
     */
    SidebarChannels: {
      /** All Meetings */
      all_meetings: number
      /** Channels */
      channels: components['schemas']['ChannelOut'][]
      /** My Meetings */
      my_meetings: number
    }
    /** SummaryOut */
    SummaryOut: {
      /** Generated At */
      generated_at?: string | null
      /**
       * Is Stale
       * @description True when the transcript changed after generation — drives the Outdated badge in the UI.
       * @default false
       */
      is_stale: boolean
      /** Keywords */
      keywords?: string[]
      /** Meeting Id */
      meeting_id: number
      /** Model */
      model?: string | null
      /** Notes */
      notes?: components['schemas']['NoteGroup'][]
      /** Outline */
      outline?: components['schemas']['OutlineEntry'][]
      /** Overview */
      overview?: string | null
      /**
       * Provider
       * @description Which provider produced this. Surfaced in the UI.
       */
      provider: string
    }
    /** TagRef */
    TagRef: {
      /** Color */
      color: string
      /** Id */
      id: number
      /** Name */
      name: string
    }
    /**
     * TranscriptHit
     * @description A transcript line that matched, with enough context to be worth showing.
     */
    TranscriptHit: {
      /** Matches */
      matches: components['schemas']['MatchRange'][]
      /** Meeting Id */
      meeting_id: number
      /** Meeting Title */
      meeting_title: string
      /** Segment Id */
      segment_id: number
      /** Snippet */
      snippet: string
      /** Speaker */
      speaker: string
      /** Start Ms */
      start_ms: number
    }
    /**
     * UserOut
     * @description The signed-in user's own record, from `/me`.
     */
    UserOut: {
      /** Avatar Url */
      avatar_url?: string | null
      /**
       * Email
       * @description Only ever returned for the current user.
       */
      email: string
      /** Id */
      id: number
      /** Name */
      name: string
    }
    /**
     * UserRef
     * @description The minimum needed to render an avatar and a name.
     *
     *     Deliberately not the full user record: this is embedded in every meeting
     *     row, so anything added here is paid for 20 times per page.
     */
    UserRef: {
      /** Avatar Url */
      avatar_url?: string | null
      /** Id */
      id: number
      /** Name */
      name: string
    }
    /** ValidationError */
    ValidationError: {
      /** Context */
      ctx?: Record<string, never>
      /** Input */
      input?: unknown
      /** Location */
      loc: (string | number)[]
      /** Message */
      msg: string
      /** Error Type */
      type: string
    }
    /**
     * Visibility
     * @enum {string}
     */
    Visibility: 'private' | 'team' | 'public'
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  health_api_health_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HealthResponse']
        }
      }
      /** @description Unexpected error. `details.request_id` correlates to logs. */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description A dependency is unavailable. */
      503: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  list_channels_api_v1_channels_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SidebarChannels']
        }
      }
      /** @description Unexpected error. `details.request_id` correlates to logs. */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  read_me_api_v1_me_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['UserOut']
        }
      }
      /** @description Unexpected error. `details.request_id` correlates to logs. */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description A dependency is unavailable. */
      503: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  list_meetings_api_v1_meetings_get: {
    parameters: {
      query?: {
        /** @description Free text across title, overview, people and transcript. */
        q?: string | null
        /** @description Host name, partial match. */
        host?: string | null
        /** @description Participant name, partial match. */
        participant?: string | null
        /** @description Inclusive start date (UTC). */
        from?: string | null
        /** @description Inclusive END date (UTC). */
        to?: string | null
        /** @description Seconds. */
        min_duration?: number | null
        /** @description Seconds. */
        max_duration?: number | null
        /** @description Tag names. ALL must match. */
        tags?: string[] | null
        /** @description Channel slug. */
        channel?: string | null
        /** @description True = has OPEN action items. */
        has_action_items?: boolean | null
        /** @description How it was captured. */
        source?: components['schemas']['MeetingSource'] | null
        /** @description One of: -created_at, -duration_seconds, -started_at, -title, created_at, duration_seconds, started_at, title */
        sort?: string
        /** @description 1-indexed page number. */
        page?: number
        /** @description Items per page. Clamped to 100. */
        page_size?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Page_MeetingListItem_']
        }
      }
      /** @description Invalid payload; `details` is keyed by field path. */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unexpected error. `details.request_id` correlates to logs. */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  create_meeting_api_v1_meetings_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['MeetingCreate']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MeetingDetail']
        }
      }
      /** @description Invalid payload; `details` is keyed by field path. */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unexpected error. `details.request_id` correlates to logs. */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  bulk_delete_api_v1_meetings_bulk_delete_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['BulkDeleteRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BulkDeleteResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
      /** @description Unexpected error. `details.request_id` correlates to logs. */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  meeting_facets_api_v1_meetings_facets_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Facets']
        }
      }
      /** @description Unexpected error. `details.request_id` correlates to logs. */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  get_meeting_api_v1_meetings__meeting_id__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        meeting_id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MeetingDetail']
        }
      }
      /** @description No meeting with this id. */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Deleted, but restorable. */
      410: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
      /** @description Unexpected error. `details.request_id` correlates to logs. */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  delete_meeting_api_v1_meetings__meeting_id__delete: {
    parameters: {
      query?: never
      header?: never
      path: {
        meeting_id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description No meeting with this id. */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Deleted, but restorable. */
      410: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
      /** @description Unexpected error. `details.request_id` correlates to logs. */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  update_meeting_api_v1_meetings__meeting_id__patch: {
    parameters: {
      query?: never
      header?: never
      path: {
        meeting_id: number
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['MeetingUpdate']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MeetingDetail']
        }
      }
      /** @description No meeting with this id. */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Deleted, but restorable. */
      410: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Invalid payload; `details` is keyed by field path. */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unexpected error. `details.request_id` correlates to logs. */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  restore_meeting_api_v1_meetings__meeting_id__restore_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        meeting_id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MeetingDetail']
        }
      }
      /** @description No meeting with this id. */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Deleted, but restorable. */
      410: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
      /** @description Unexpected error. `details.request_id` correlates to logs. */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  regenerate_summary_api_v1_meetings__meeting_id__summary_regenerate_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        meeting_id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SummaryOut']
        }
      }
      /** @description No meeting with this id. */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Deleted, but restorable. */
      410: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
      /** @description Rate limit exceeded. */
      429: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unexpected error. `details.request_id` correlates to logs. */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  search_api_v1_search_get: {
    parameters: {
      query: {
        /** @description Search term. Treated literally, not as a pattern. */
        q: string
        /** @description Max hits per group. */
        limit?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SearchResults']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
      /** @description Unexpected error. `details.request_id` correlates to logs. */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
}
