/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/health': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Service health
     * @description Reports liveness, database reachability and the active configuration. Returns **503** when the database cannot be reached, so a host's health check takes the instance out of rotation rather than serving errors.
     */
    get: operations['health_api_health_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/me': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Current user
     * @description Authentication is out of scope for this build: this returns the seeded default user. It is a dependency rather than a constant, so swapping in real auth changes one function and no route signatures.
     */
    get: operations['read_me_api_v1_me_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/meetings': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List meetings
     * @description Paginated, newest first. Returns the LIGHT row shape — no transcript and no full summary. Use `GET /meetings/{id}` for detail.
     */
    get: operations['list_meetings_api_v1_meetings_get']
    put?: never
    /**
     * Create a meeting
     * @description Creates an empty meeting. Transcript ingestion happens separately.
     */
    post: operations['create_meeting_api_v1_meetings_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/meetings/bulk-delete': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Delete several meetings
     * @description Reports per-id failures rather than aborting the batch, so the client can say '2 of 3 deleted' instead of leaving the user guessing.
     */
    post: operations['bulk_delete_api_v1_meetings_bulk_delete_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/meetings/{meeting_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get a meeting
     * @description 404 if the meeting never existed; **410** if it was deleted, since a deleted meeting is restorable and the client can offer that.
     */
    get: operations['get_meeting_api_v1_meetings__meeting_id__get']
    put?: never
    post?: never
    /**
     * Delete a meeting
     * @description Soft delete. The meeting disappears from lists but is restorable.
     */
    delete: operations['delete_meeting_api_v1_meetings__meeting_id__delete']
    options?: never
    head?: never
    /**
     * Update a meeting
     * @description Partial update — omitted fields are left untouched.
     */
    patch: operations['update_meeting_api_v1_meetings__meeting_id__patch']
    trace?: never
  }
  '/api/v1/meetings/{meeting_id}/restore': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Restore a deleted meeting
     * @description Undoes a soft delete. Backs the 6-second Undo affordance in the UI.
     */
    post: operations['restore_meeting_api_v1_meetings__meeting_id__restore_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/meetings/{meeting_id}/summary/regenerate': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Regenerate a meeting summary
     * @description Rate limited to 10 requests per minute — this is the endpoint that calls a model, and an accidental double-click should not double the bill.
     */
    post: operations['regenerate_summary_api_v1_meetings__meeting_id__summary_regenerate_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /**
     * ActionItemCounts
     * @description Pre-aggregated so the row does not have to count client-side.
     */
    ActionItemCounts: {
      /**
       * Completed
       * @default 0
       */
      completed: number
      /**
       * Open
       * @default 0
       */
      open: number
    }
    /** BulkDeleteRequest */
    BulkDeleteRequest: {
      /** Ids */
      ids: number[]
    }
    /** BulkDeleteResponse */
    BulkDeleteResponse: {
      /** Deleted */
      deleted: number
      /**
       * Failed
       * @description Ids that could not be deleted, e.g. already gone.
       */
      failed?: number[]
    }
    /** ErrorDetail */
    ErrorDetail: {
      /**
       * Code
       * @description Stable machine-readable identifier; safe to branch on.
       */
      code: string
      /**
       * Details
       * @description Field-level errors, keyed by dotted path, when applicable.
       */
      details?: {
        [key: string]: unknown
      }
      /**
       * Message
       * @description Human-readable explanation. Wording may change.
       */
      message: string
    }
    /**
     * ErrorResponse
     * @description Every non-2xx response body in the API has this shape.
     *
     *     Nested under a single `error` key rather than flattened, so a client can
     *     tell an error from a successful payload without inspecting the status code —
     *     which matters for the fetch wrapper in T-06.4.
     */
    ErrorResponse: {
      error: components['schemas']['ErrorDetail']
    }
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][]
    }
    /** HealthResponse */
    HealthResponse: {
      /**
       * Ai Provider
       * @description Active summary/extraction provider.
       */
      ai_provider: string
      /**
       * Db
       * @description Result of a real SELECT 1.
       * @enum {string}
       */
      db: 'up' | 'down'
      /**
       * Status
       * @description Overall service state.
       * @enum {string}
       */
      status: 'ok' | 'degraded'
      /**
       * Version
       * @description Deployed application version.
       */
      version: string
    }
    /**
     * MediaType
     * @enum {string}
     */
    MediaType: 'audio' | 'video' | 'none'
    /**
     * MeetingCreate
     * @description Creating a meeting from the form, a paste, or an upload.
     */
    MeetingCreate: {
      /** Channel Id */
      channel_id?: number | null
      /** Description */
      description?: string | null
      /**
       * Language
       * @default en
       */
      language: string
      /** Participant Names */
      participant_names?: string[]
      /** @default manual */
      source: components['schemas']['MeetingSource']
      /**
       * Started At
       * @description Defaults to now when omitted.
       */
      started_at?: string | null
      /** Title */
      title: string
      /** @default private */
      visibility: components['schemas']['Visibility']
    }
    /**
     * MeetingDetail
     * @description The Notepad payload. Heavy, and only ever returned for a single meeting.
     *
     *     Transcript segments are NOT here — they are paginated separately via
     *     `/meetings/{id}/transcript` (T-17.2), because a 55-minute meeting is ~1,200
     *     segments and shipping them inline makes the first paint wait on all of them.
     */
    MeetingDetail: {
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
      /** Description */
      description?: string | null
      /** Duration Seconds */
      duration_seconds: number
      host: components['schemas']['UserRef']
      /** Id */
      id: number
      /** Keywords */
      keywords?: string[]
      /** Language */
      language: string
      media_type: components['schemas']['MediaType']
      /** Media Url */
      media_url?: string | null
      /** Participants */
      participants?: components['schemas']['ParticipantRef'][]
      processing_status: components['schemas']['ProcessingStatus']
      /**
       * Segment Count
       * @default 0
       */
      segment_count: number
      source: components['schemas']['MeetingSource']
      /**
       * Started At
       * Format: date-time
       */
      started_at: string
      /** Tags */
      tags?: components['schemas']['TagRef'][]
      /** Title */
      title: string
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string
      visibility: components['schemas']['Visibility']
    }
    /**
     * MeetingListItem
     * @description One row of the Notebook. LIGHT — no transcript, no full summary.
     *
     *     Carries a one-line `overview_preview` rather than the whole overview, since
     *     the row clamps it to a single line anyway.
     */
    MeetingListItem: {
      action_item_counts: components['schemas']['ActionItemCounts']
      /** Duration Seconds */
      duration_seconds: number
      /**
       * Has Media
       * @default false
       */
      has_media: boolean
      host: components['schemas']['UserRef']
      /** Id */
      id: number
      /** Keywords */
      keywords?: string[]
      /** @default none */
      media_type: components['schemas']['MediaType']
      /** Overview Preview */
      overview_preview?: string | null
      /**
       * Participant Count
       * @default 0
       */
      participant_count: number
      /**
       * Participants
       * @description Capped; `participant_count` has the true total.
       */
      participants?: components['schemas']['ParticipantRef'][]
      /**
       * Started At
       * Format: date-time
       */
      started_at: string
      /** Tags */
      tags?: components['schemas']['TagRef'][]
      /** Title */
      title: string
    }
    /**
     * MeetingSource
     * @enum {string}
     */
    MeetingSource: 'upload' | 'manual' | 'seed' | 'integration'
    /**
     * MeetingUpdate
     * @description Partial update. Every field optional; unset fields are left alone.
     */
    MeetingUpdate: {
      /** Channel Id */
      channel_id?: number | null
      /** Description */
      description?: string | null
      /** Language */
      language?: string | null
      /** Started At */
      started_at?: string | null
      /** Title */
      title?: string | null
      visibility?: components['schemas']['Visibility'] | null
    }
    /**
     * NoteGroup
     * @description Bullet notes, grouped under their outline chapter.
     */
    NoteGroup: {
      /** Bullets */
      bullets?: string[]
      /** Chapter */
      chapter?: string | null
    }
    /**
     * OutlineEntry
     * @description One chapter of the Meeting Outline.
     */
    OutlineEntry: {
      /**
       * Sequence
       * @default 0
       */
      sequence: number
      /** Start Ms */
      start_ms: number
      /** Title */
      title: string
    }
    /** Page[MeetingListItem] */
    Page_MeetingListItem_: {
      /** Has Next */
      readonly has_next: boolean
      /** Items */
      items: components['schemas']['MeetingListItem'][]
      /**
       * Page
       * @description 1-indexed page number.
       */
      page: number
      /** Page Size */
      page_size: number
      /**
       * Total
       * @description Total matching rows, ignoring pagination.
       */
      total: number
      /** Total Pages */
      readonly total_pages: number
    }
    /**
     * ParticipantRef
     * @description Enough to render an avatar in a group.
     */
    ParticipantRef: {
      /** Avatar Url */
      avatar_url?: string | null
      /** Display Name */
      display_name: string
      /** Id */
      id: number
    }
    /**
     * ProcessingStatus
     * @enum {string}
     */
    ProcessingStatus: 'pending' | 'processing' | 'ready' | 'failed'
    /** SummaryOut */
    SummaryOut: {
      /** Generated At */
      generated_at?: string | null
      /**
       * Is Stale
       * @description True when the transcript changed after generation — drives the Outdated badge in the UI.
       * @default false
       */
      is_stale: boolean
      /** Keywords */
      keywords?: string[]
      /** Meeting Id */
      meeting_id: number
      /** Model */
      model?: string | null
      /** Notes */
      notes?: components['schemas']['NoteGroup'][]
      /** Outline */
      outline?: components['schemas']['OutlineEntry'][]
      /** Overview */
      overview?: string | null
      /**
       * Provider
       * @description Which provider produced this. Surfaced in the UI.
       */
      provider: string
    }
    /** TagRef */
    TagRef: {
      /** Color */
      color: string
      /** Id */
      id: number
      /** Name */
      name: string
    }
    /**
     * UserOut
     * @description The signed-in user's own record, from `/me`.
     */
    UserOut: {
      /** Avatar Url */
      avatar_url?: string | null
      /**
       * Email
       * @description Only ever returned for the current user.
       */
      email: string
      /** Id */
      id: number
      /** Name */
      name: string
    }
    /**
     * UserRef
     * @description The minimum needed to render an avatar and a name.
     *
     *     Deliberately not the full user record: this is embedded in every meeting
     *     row, so anything added here is paid for 20 times per page.
     */
    UserRef: {
      /** Avatar Url */
      avatar_url?: string | null
      /** Id */
      id: number
      /** Name */
      name: string
    }
    /** ValidationError */
    ValidationError: {
      /** Context */
      ctx?: Record<string, never>
      /** Input */
      input?: unknown
      /** Location */
      loc: (string | number)[]
      /** Message */
      msg: string
      /** Error Type */
      type: string
    }
    /**
     * Visibility
     * @enum {string}
     */
    Visibility: 'private' | 'team' | 'public'
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  health_api_health_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HealthResponse']
        }
      }
      /** @description Unexpected error. `details.request_id` correlates to logs. */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description A dependency is unavailable. */
      503: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  read_me_api_v1_me_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['UserOut']
        }
      }
      /** @description Unexpected error. `details.request_id` correlates to logs. */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description A dependency is unavailable. */
      503: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  list_meetings_api_v1_meetings_get: {
    parameters: {
      query?: {
        /** @description Case-insensitive title match. */
        q?: string | null
        /** @description One of: -created_at, -duration_seconds, -started_at, -title, created_at, duration_seconds, started_at, title */
        sort?: string
        /** @description 1-indexed page number. */
        page?: number
        /** @description Items per page. Clamped to 100. */
        page_size?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Page_MeetingListItem_']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
      /** @description Unexpected error. `details.request_id` correlates to logs. */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  create_meeting_api_v1_meetings_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['MeetingCreate']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MeetingDetail']
        }
      }
      /** @description Invalid payload; `details` is keyed by field path. */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unexpected error. `details.request_id` correlates to logs. */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  bulk_delete_api_v1_meetings_bulk_delete_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['BulkDeleteRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BulkDeleteResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
      /** @description Unexpected error. `details.request_id` correlates to logs. */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  get_meeting_api_v1_meetings__meeting_id__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        meeting_id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MeetingDetail']
        }
      }
      /** @description No meeting with this id. */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Deleted, but restorable. */
      410: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
      /** @description Unexpected error. `details.request_id` correlates to logs. */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  delete_meeting_api_v1_meetings__meeting_id__delete: {
    parameters: {
      query?: never
      header?: never
      path: {
        meeting_id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description No meeting with this id. */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Deleted, but restorable. */
      410: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
      /** @description Unexpected error. `details.request_id` correlates to logs. */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  update_meeting_api_v1_meetings__meeting_id__patch: {
    parameters: {
      query?: never
      header?: never
      path: {
        meeting_id: number
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['MeetingUpdate']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MeetingDetail']
        }
      }
      /** @description No meeting with this id. */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Deleted, but restorable. */
      410: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Invalid payload; `details` is keyed by field path. */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unexpected error. `details.request_id` correlates to logs. */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  restore_meeting_api_v1_meetings__meeting_id__restore_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        meeting_id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MeetingDetail']
        }
      }
      /** @description No meeting with this id. */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Deleted, but restorable. */
      410: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
      /** @description Unexpected error. `details.request_id` correlates to logs. */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  regenerate_summary_api_v1_meetings__meeting_id__summary_regenerate_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        meeting_id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SummaryOut']
        }
      }
      /** @description No meeting with this id. */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Deleted, but restorable. */
      410: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
      /** @description Rate limit exceeded. */
      429: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unexpected error. `details.request_id` correlates to logs. */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
}
