/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/health': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Service health
     * @description Reports liveness, database reachability and the active configuration. Returns **503** when the database cannot be reached, so a host's health check takes the instance out of rotation rather than serving errors.
     */
    get: operations['health_api_health_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/channels': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List channels with counts
     * @description Channels plus the two built-in views. Counts exclude deleted meetings, and a channel with no meetings still appears, showing zero.
     */
    get: operations['list_channels_api_v1_channels_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/me': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Current user
     * @description Authentication is out of scope for this build: this returns the seeded default user. It is a dependency rather than a constant, so swapping in real auth changes one function and no route signatures.
     */
    get: operations['read_me_api_v1_me_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/meetings': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List meetings
     * @description Paginated, newest first. Returns the LIGHT row shape — no transcript and no full summary; use `GET /meetings/{id}` for detail.
     *
     *     `from` and `to` are inclusive dates in UTC: `to=2026-07-26` includes everything that happened ON the 26th.
     *
     *     `q` matches the title, the overview, participant names and the transcript. When the hit came from the transcript — and only then — the row carries `match_context` explaining why.
     */
    get: operations['list_meetings_api_v1_meetings_get']
    put?: never
    /**
     * Create a meeting
     * @description Creates an empty meeting. Transcript ingestion happens separately.
     */
    post: operations['create_meeting_api_v1_meetings_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/meetings/action-items/{item_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /**
     * Delete an action item
     * @description Returns the deleted item, so the client can offer Undo by re-creating it. A hard delete: one line of text with no children does not need the soft-delete machinery meetings have.
     */
    delete: operations['delete_action_item_api_v1_meetings_action_items__item_id__delete']
    options?: never
    head?: never
    /**
     * Edit an action item
     * @description A partial edit: text, assignee, due date or status. `completed_at` is derived from the status rather than accepted from the client, so the two cannot disagree. Sending `null` CLEARS a nullable field — absent and null are different requests.
     */
    patch: operations['update_action_item_api_v1_meetings_action_items__item_id__patch']
    trace?: never
  }
  '/api/v1/meetings/bulk-delete': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Delete several meetings
     * @description Reports per-id failures rather than aborting the batch, so the client can say '2 of 3 deleted' instead of leaving the user guessing.
     */
    post: operations['bulk_delete_api_v1_meetings_bulk_delete_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/meetings/bulk-restore': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Restore several meetings
     * @description The undo half of a bulk delete. Reports per-id failures the same way, so an Undo that only half-works says so rather than appearing to fail.
     */
    post: operations['bulk_restore_api_v1_meetings_bulk_restore_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/meetings/facets': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Available filter values
     * @description Distinct hosts, participants, tags and channels across non-deleted meetings, plus the duration bounds. Derived from real data so the filter panel can never offer an option that matches nothing.
     */
    get: operations['meeting_facets_api_v1_meetings_facets_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/meetings/import': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Create a meeting with a transcript
     * @description Takes the segments the user confirmed in the preview. Speakers are created from the distinct names in first-appearance order, the duration is derived from the last segment, and anyone who spoke is added as a participant. All in one transaction: a meeting with half a transcript looks successful and is not.
     */
    post: operations['import_meeting_api_v1_meetings_import_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/meetings/parse': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Parse a transcript without saving anything
     * @description Backs the upload and paste previews (T-26.7). Nothing is written — this answers 'what would we create', so the user can confirm it or correct the speakers first.
     *
     *     The EXTENSION chooses the parser; it does not certify the content. A binary file renamed to `.txt` reaches the text parser and is refused on what it actually contains.
     */
    post: operations['parse_transcript_preview_api_v1_meetings_parse_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/meetings/segments/{segment_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    /**
     * Edit a transcript segment
     * @description Sets `is_edited`, captures the original text once so the edit is reversible, and marks the summary stale — a summary derived from text that has since changed is confidently wrong.
     */
    patch: operations['update_segment_api_v1_meetings_segments__segment_id__patch']
    trace?: never
  }
  '/api/v1/meetings/speakers/{speaker_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    /**
     * Rename a speaker
     * @description One UPDATE, however long the transcript is: the label lives on `speakers` and segments reference it.
     */
    patch: operations['update_speaker_api_v1_meetings_speakers__speaker_id__patch']
    trace?: never
  }
  '/api/v1/meetings/{meeting_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get a meeting
     * @description 404 if the meeting never existed; **410** if it was deleted, since a deleted meeting is restorable and the client can offer that.
     */
    get: operations['get_meeting_api_v1_meetings__meeting_id__get']
    put?: never
    post?: never
    /**
     * Delete a meeting
     * @description Soft delete. The meeting disappears from lists but is restorable.
     */
    delete: operations['delete_meeting_api_v1_meetings__meeting_id__delete']
    options?: never
    head?: never
    /**
     * Update a meeting
     * @description Partial update — omitted fields are left untouched.
     */
    patch: operations['update_meeting_api_v1_meetings__meeting_id__patch']
    trace?: never
  }
  '/api/v1/meetings/{meeting_id}/action-items': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List a meeting's action items
     * @description Ordered as they were raised. T-24 owns the full CRUD; this backs the previews.
     */
    get: operations['list_action_items_api_v1_meetings__meeting_id__action_items_get']
    put?: never
    /**
     * Add an action item
     * @description Appended after the extracted items and marked `manual`, so a task somebody typed is distinguishable from one the model guessed.
     */
    post: operations['create_action_item_api_v1_meetings__meeting_id__action_items_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/meetings/{meeting_id}/media': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Stream a meeting's audio
     * @description Supports HTTP Range (206). Without it a browser can play the file but cannot SEEK — the scrubber silently snaps back, with no error anywhere. `Accept-Ranges: bytes` is always advertised.
     */
    get: operations['get_media_api_v1_meetings__meeting_id__media_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/meetings/{meeting_id}/restore': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Restore a deleted meeting
     * @description Undoes a soft delete. Backs the 6-second Undo affordance in the UI.
     */
    post: operations['restore_meeting_api_v1_meetings__meeting_id__restore_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/meetings/{meeting_id}/speakers': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Every speaker in a meeting */
    get: operations['get_speakers_api_v1_meetings__meeting_id__speakers_get']
    put?: never
    /**
     * Add a speaker
     * @description For a voice the diariser missed. The colour index continues the meeting's sequence, so the new speaker is visibly distinct from the ones already on screen.
     */
    post: operations['create_speaker_api_v1_meetings__meeting_id__speakers_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/meetings/{meeting_id}/summary': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get a meeting summary
     * @description The stored summary. T-20 builds the full panel on this; the details drawer uses the overview alone.
     */
    get: operations['get_summary_api_v1_meetings__meeting_id__summary_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/meetings/{meeting_id}/summary/regenerate': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Regenerate a meeting summary
     * @description Rate limited to 10 requests per minute — this is the endpoint that calls a model, and an accidental double-click should not double the bill.
     */
    post: operations['regenerate_summary_api_v1_meetings__meeting_id__summary_regenerate_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/meetings/{meeting_id}/transcript': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * A page of transcript segments
     * @description Cursor-paginated on `sequence`, because a 55-minute meeting is ~1,200 segments. Speakers are sent BY REFERENCE once per page rather than inlined on every segment.
     *
     *     `?q=` filters server-side and returns match offsets, so a long transcript does not have to be downloaded before it can be searched.
     */
    get: operations['get_transcript_api_v1_meetings__meeting_id__transcript_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/search': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Search meetings and transcripts
     * @description FTS5-ranked, grouped into title matches and transcript matches. Snippets carry match RANGES rather than markup — the client wraps them, so transcript text containing HTML is rendered rather than executed. Queries shorter than two characters return nothing.
     */
    get: operations['search_api_v1_search_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/users': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List workspace members
     * @description Everyone in the (single, seeded) workspace, for the Team page. Emails are deliberately absent — those are only ever returned for the current user via /me.
     */
    get: operations['list_users_api_v1_users_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /**
     * ActionItemCounts
     * @description Pre-aggregated so the row does not have to count client-side.
     */
    ActionItemCounts: {
      /**
       * Completed
       * @default 0
       */
      completed: number
      /**
       * Open
       * @default 0
       */
      open: number
    }
    /**
     * ActionItemCreate
     * @description A manually added item (T-24.5).
     */
    ActionItemCreate: {
      /** Assignee Participant Id */
      assignee_participant_id?: number | null
      /** Due Date */
      due_date?: string | null
      /** Start Ms */
      start_ms?: number | null
      /** Text */
      text: string
    }
    /**
     * ActionItemOut
     * @description One action item, with everything the Notepad's list draws (T-24).
     */
    ActionItemOut: {
      /** Assignee Avatar Url */
      assignee_avatar_url: string | null
      /** Assignee Name */
      assignee_name: string | null
      /** Assignee Participant Id */
      assignee_participant_id: number | null
      /** Due Date */
      due_date: string | null
      /** Id */
      id: number
      /** Meeting Id */
      meeting_id: number
      source: components['schemas']['ActionItemSource']
      /** Start Ms */
      start_ms: number | null
      status: components['schemas']['ActionItemStatus']
      /** Text */
      text: string
    }
    /**
     * ActionItemSource
     * @enum {string}
     */
    ActionItemSource: 'ai' | 'manual'
    /**
     * ActionItemStatus
     * @enum {string}
     */
    ActionItemStatus: 'open' | 'completed'
    /**
     * ActionItemUpdate
     * @description A partial edit: text, assignee, due date, or the checkbox.
     *
     *     Every field is optional, and `None` is a MEANINGFUL value for the nullable
     *     ones — clearing an assignee is a real edit. The two are told apart with
     *     `model_fields_set` rather than by treating `None` as "absent", which would
     *     make unassigning impossible.
     */
    ActionItemUpdate: {
      /** Assignee Participant Id */
      assignee_participant_id?: number | null
      /** Due Date */
      due_date?: string | null
      status?: components['schemas']['ActionItemStatus'] | null
      /** Text */
      text?: string | null
    }
    /** Body_parse_transcript_preview_api_v1_meetings_parse_post */
    Body_parse_transcript_preview_api_v1_meetings_parse_post: {
      /**
       * Extension
       * @description Which parser to use for pasted text.
       * @default txt
       */
      extension: string
      /**
       * File
       * @description A .txt, .vtt, .srt or .json file.
       */
      file?: string | null
      /**
       * Text
       * @description Pasted transcript text.
       */
      text?: string | null
    }
    /** BulkDeleteRequest */
    BulkDeleteRequest: {
      /** Ids */
      ids: number[]
    }
    /** BulkDeleteResponse */
    BulkDeleteResponse: {
      /** Deleted */
      deleted: number
      /**
       * Failed
       * @description Ids that could not be deleted, e.g. already gone.
       */
      failed: number[]
    }
    /**
     * BulkRestoreResponse
     * @description The undo half of a bulk delete (T-14.5).
     *
     *     Separate from `BulkDeleteResponse` rather than reusing it with a renamed
     *     field: they mean different things, and a shared shape would make
     *     `{"deleted": 3}` the response to a restore.
     */
    BulkRestoreResponse: {
      /**
       * Failed
       * @description Ids that could not be restored, e.g. never deleted.
       */
      failed: number[]
      /** Restored */
      restored: number
    }
    /**
     * ChannelOut
     * @description A sidebar channel, with its meeting count.
     *
     *     The count is what makes the rail feel alive rather than decorative, and it
     *     is aggregated server-side — the alternative is the client fetching every
     *     meeting just to group them.
     */
    ChannelOut: {
      /** Icon */
      icon?: string | null
      /** Id */
      id: number
      /** Is Private */
      is_private: boolean
      /**
       * Meeting Count
       * @description Meetings in this channel, excluding deleted.
       */
      meeting_count: number
      /** Name */
      name: string
      /** Slug */
      slug: string
    }
    /**
     * ChannelRef
     * @description Just enough to name the channel a meeting sits in.
     */
    ChannelRef: {
      /** Id */
      id: number
      /** Name */
      name: string
      /** Slug */
      slug: string
    }
    /** ErrorDetail */
    ErrorDetail: {
      /**
       * Code
       * @description Stable machine-readable identifier; safe to branch on.
       */
      code: string
      /**
       * Details
       * @description Field-level errors, keyed by dotted path, when applicable.
       */
      details?: {
        [key: string]: unknown
      }
      /**
       * Message
       * @description Human-readable explanation. Wording may change.
       */
      message: string
    }
    /**
     * ErrorResponse
     * @description Every non-2xx response body in the API has this shape.
     *
     *     Nested under a single `error` key rather than flattened, so a client can
     *     tell an error from a successful payload without inspecting the status code —
     *     which matters for the fetch wrapper in T-06.4.
     */
    ErrorResponse: {
      error: components['schemas']['ErrorDetail']
    }
    /**
     * Facets
     * @description Available filter values, derived from real data (T-11.8).
     *
     *     Sent so the filter panel can never offer an option that matches nothing,
     *     which is how a filter panel loses the user's trust on the first click.
     */
    Facets: {
      /** Channels */
      channels: string[]
      /** Hosts */
      hosts: string[]
      /** Max Duration */
      max_duration: number
      /** Min Duration */
      min_duration: number
      /** Participants */
      participants: string[]
      /** Tags */
      tags: string[]
    }
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][]
    }
    /** HealthResponse */
    HealthResponse: {
      /**
       * Ai Provider
       * @description Active summary/extraction provider.
       */
      ai_provider: string
      /**
       * Db
       * @description Result of a real SELECT 1.
       * @enum {string}
       */
      db: 'up' | 'down'
      /**
       * Status
       * @description Overall service state.
       * @enum {string}
       */
      status: 'ok' | 'degraded'
      /**
       * Version
       * @description Deployed application version.
       */
      version: string
    }
    /**
     * ImportedSegment
     * @description One line of a transcript being imported (T-26.7).
     */
    ImportedSegment: {
      /** End Ms */
      end_ms: number
      /** Speaker */
      speaker: string
      /** Start Ms */
      start_ms: number
      /** Text */
      text: string
    }
    /**
     * MatchContext
     * @description Why a meeting matched, when the reason is not visible in the row (T-11.3).
     *
     *     Present ONLY when the hit came from the transcript. A title match needs no
     *     explanation — the user can read it — but a transcript match looks like a
     *     false positive unless the row shows the line that caused it.
     */
    MatchContext: {
      /** Snippet */
      snippet: string
      /** Speaker */
      speaker: string
      /** Start Ms */
      start_ms: number
    }
    /**
     * MatchRange
     * @description Character offsets of a matched term within some text.
     *
     *     Shared by global search and the transcript endpoints. It lived in both
     *     modules as separate identical classes, which made openapi-typescript emit
     *     `app__schemas__search__MatchRange` and `app__schemas__transcript__MatchRange`
     *     — two mangled names for one concept, and a compile error in any client that
     *     imported "MatchRange".
     */
    MatchRange: {
      /** End */
      end: number
      /** Start */
      start: number
    }
    /**
     * MediaType
     * @enum {string}
     */
    MediaType: 'audio' | 'video' | 'none'
    /**
     * MeetingCreate
     * @description Creating a meeting from the form, a paste, or an upload.
     */
    MeetingCreate: {
      /** Channel Id */
      channel_id?: number | null
      /** Description */
      description?: string | null
      /**
       * Language
       * @default en
       */
      language: string
      /** Participant Names */
      participant_names?: string[]
      /** @default manual */
      source: components['schemas']['MeetingSource']
      /**
       * Started At
       * @description Defaults to now when omitted.
       */
      started_at?: string | null
      /** Title */
      title: string
      /** @default private */
      visibility: components['schemas']['Visibility']
    }
    /**
     * MeetingDetail
     * @description The Notepad payload. Heavy, and only ever returned for a single meeting.
     *
     *     Transcript segments are NOT here — they are paginated separately via
     *     `/meetings/{id}/transcript` (T-17.2), because a 55-minute meeting is ~1,200
     *     segments and shipping them inline makes the first paint wait on all of them.
     */
    MeetingDetail: {
      channel?: components['schemas']['ChannelRef'] | null
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
      /** Description */
      description?: string | null
      /** Duration Seconds */
      duration_seconds: number
      host: components['schemas']['UserRef']
      /** Id */
      id: number
      /** Keywords */
      keywords?: string[]
      /** Language */
      language: string
      media_type: components['schemas']['MediaType']
      /** Media Url */
      media_url?: string | null
      /** Participants */
      participants?: components['schemas']['ParticipantDetail'][]
      processing_status: components['schemas']['ProcessingStatus']
      /**
       * Segment Count
       * @default 0
       */
      segment_count: number
      source: components['schemas']['MeetingSource']
      /**
       * Started At
       * Format: date-time
       */
      started_at: string
      /** Tags */
      tags?: components['schemas']['TagRef'][]
      /** Title */
      title: string
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string
      visibility: components['schemas']['Visibility']
    }
    /**
     * MeetingHit
     * @description A meeting whose title or overview matched.
     */
    MeetingHit: {
      /** Duration Seconds */
      duration_seconds: number
      /** Id */
      id: number
      /** Matches */
      matches: components['schemas']['MatchRange'][]
      /** Started At */
      started_at: string
      /** Title */
      title: string
    }
    /**
     * MeetingImport
     * @description A meeting created WITH a transcript (T-26.7).
     *
     *     The segments are the ones the user confirmed in the preview, sent back
     *     rather than re-parsed: the preview is a contract, and re-reading the file
     *     would let a second parse disagree with what was on screen. They are
     *     re-validated here, because the client is still the client.
     */
    MeetingImport: {
      /** Channel Id */
      channel_id?: number | null
      /** Description */
      description?: string | null
      /**
       * Language
       * @default en
       */
      language: string
      /** Participant Names */
      participant_names?: string[]
      /** Segments */
      segments: components['schemas']['ImportedSegment'][]
      /** @default manual */
      source: components['schemas']['MeetingSource']
      /**
       * Started At
       * @description Defaults to now when omitted.
       */
      started_at?: string | null
      /** Title */
      title: string
      /** @default private */
      visibility: components['schemas']['Visibility']
    }
    /**
     * MeetingListItem
     * @description One row of the Notebook. LIGHT — no transcript, no full summary.
     *
     *     Carries a one-line `overview_preview` rather than the whole overview, since
     *     the row clamps it to a single line anyway.
     */
    MeetingListItem: {
      action_item_counts: components['schemas']['ActionItemCounts']
      /** Duration Seconds */
      duration_seconds: number
      /**
       * Has Media
       * @default false
       */
      has_media: boolean
      host: components['schemas']['UserRef']
      /** Id */
      id: number
      /** Keywords */
      keywords?: string[]
      match_context?: components['schemas']['MatchContext'] | null
      /** @default none */
      media_type: components['schemas']['MediaType']
      /** Overview Preview */
      overview_preview?: string | null
      /**
       * Participant Count
       * @default 0
       */
      participant_count: number
      /**
       * Participants
       * @description Capped; `participant_count` has the true total.
       */
      participants?: components['schemas']['ParticipantRef'][]
      /**
       * Started At
       * Format: date-time
       */
      started_at: string
      /** Tags */
      tags?: components['schemas']['TagRef'][]
      /** Title */
      title: string
    }
    /**
     * MeetingSource
     * @enum {string}
     */
    MeetingSource: 'upload' | 'manual' | 'seed' | 'integration'
    /**
     * MeetingUpdate
     * @description Partial update. Every field optional; unset fields are left alone.
     */
    MeetingUpdate: {
      /** Channel Id */
      channel_id?: number | null
      /** Description */
      description?: string | null
      /** Host Participant Id */
      host_participant_id?: number | null
      /** Language */
      language?: string | null
      /** Participant Names */
      participant_names?: string[] | null
      /** Started At */
      started_at?: string | null
      /** Title */
      title?: string | null
      visibility?: components['schemas']['Visibility'] | null
    }
    /**
     * NoteGroup
     * @description Bullet notes, grouped under their outline chapter.
     */
    NoteGroup: {
      /** Bullets */
      bullets: string[]
      /** Chapter */
      chapter: string | null
    }
    /**
     * OutlineEntry
     * @description One chapter of the Meeting Outline.
     */
    OutlineEntry: {
      /**
       * Sequence
       * @default 0
       */
      sequence: number
      /** Start Ms */
      start_ms: number
      /** Title */
      title: string
    }
    /** Page[MeetingListItem] */
    Page_MeetingListItem_: {
      /** Has Next */
      readonly has_next: boolean
      /** Items */
      items: components['schemas']['MeetingListItem'][]
      /**
       * Page
       * @description 1-indexed page number.
       */
      page: number
      /** Page Size */
      page_size: number
      /**
       * Total
       * @description Total matching rows, ignoring pagination.
       */
      total: number
      /** Total Pages */
      readonly total_pages: number
    }
    /** Page[TeamMemberOut] */
    Page_TeamMemberOut_: {
      /** Has Next */
      readonly has_next: boolean
      /** Items */
      items: components['schemas']['TeamMemberOut'][]
      /**
       * Page
       * @description 1-indexed page number.
       */
      page: number
      /** Page Size */
      page_size: number
      /**
       * Total
       * @description Total matching rows, ignoring pagination.
       */
      total: number
      /** Total Pages */
      readonly total_pages: number
    }
    /**
     * ParticipantDetail
     * @description A participant, as the details drawer shows them (T-15.8, T-15.9).
     *
     *     Richer than `ParticipantRef`, which exists to render an avatar in a group
     *     and deliberately carries nothing else — a Notebook page holds twenty rows
     *     and would otherwise ship attendance data for a hundred people nobody looks
     *     at.
     */
    ParticipantDetail: {
      /** Attended */
      attended: boolean
      /** Avatar Url */
      avatar_url?: string | null
      /** Color Index */
      color_index?: number | null
      /** Display Name */
      display_name: string
      /** Email */
      email?: string | null
      /** Id */
      id: number
      /** Talk Seconds */
      talk_seconds: number
      /** User Id */
      user_id?: number | null
    }
    /**
     * ParticipantRef
     * @description Enough to render an avatar in a group.
     */
    ParticipantRef: {
      /** Avatar Url */
      avatar_url?: string | null
      /** Display Name */
      display_name: string
      /** Id */
      id: number
    }
    /**
     * ProcessingStatus
     * @enum {string}
     */
    ProcessingStatus: 'pending' | 'processing' | 'ready' | 'failed'
    /**
     * SearchResults
     * @description Grouped, because the two kinds of hit mean different things.
     *
     *     A title match is "this meeting is about X"; a transcript match is "X was
     *     said at 18:42". Flattening them loses that distinction and makes the
     *     dropdown harder to scan.
     */
    SearchResults: {
      /** Meetings */
      meetings: components['schemas']['MeetingHit'][]
      /** Query */
      query: string
      /**
       * Total
       * @description Combined count across both groups.
       */
      total: number
      /** Transcripts */
      transcripts: components['schemas']['TranscriptHit'][]
    }
    /**
     * SegmentOut
     * @description One transcript line.
     */
    SegmentOut: {
      /** End Ms */
      end_ms: number
      /** Id */
      id: number
      /** Is Edited */
      is_edited: boolean
      /** Matches */
      matches: components['schemas']['MatchRange'][] | null
      /** Original Text */
      original_text: string | null
      /** Sequence */
      sequence: number
      /** Speaker Id */
      speaker_id: number
      /** Start Ms */
      start_ms: number
      /** Text */
      text: string
    }
    /**
     * SegmentUpdate
     * @description Edit a line's text, reassign its speaker, or both (T-17.5).
     */
    SegmentUpdate: {
      /** Speaker Id */
      speaker_id?: number | null
      /** Text */
      text?: string | null
    }
    /**
     * SidebarChannels
     * @description Everything the rail's CHANNELS section needs, in one request.
     *
     *     The two built-in views are counts rather than channel rows — "My Meetings"
     *     and "All Meetings" are filters over the same data, not stored channels —
     *     so returning them alongside avoids the client making three calls to render
     *     one list.
     */
    SidebarChannels: {
      /** All Meetings */
      all_meetings: number
      /** Channels */
      channels: components['schemas']['ChannelOut'][]
      /** My Meetings */
      my_meetings: number
    }
    /**
     * SpeakerCreate
     * @description A voice the diariser did not find (T-25.6).
     */
    SpeakerCreate: {
      /** Label */
      label: string
      /** Participant Id */
      participant_id?: number | null
    }
    /**
     * SpeakerRef
     * @description A speaker, sent once per page rather than once per segment.
     */
    SpeakerRef: {
      /** Color Index */
      color_index: number
      /** Id */
      id: number
      /** Label */
      label: string
      /** Participant Id */
      participant_id: number | null
      /** Segment Count */
      segment_count: number
      /** Talk Ms */
      talk_ms: number
    }
    /**
     * SpeakerUpdate
     * @description Rename a speaker across the whole meeting (T-17.6).
     */
    SpeakerUpdate: {
      /** Label */
      label?: string | null
      /** Participant Id */
      participant_id?: number | null
    }
    /** SummaryOut */
    SummaryOut: {
      /** Generated At */
      generated_at?: string | null
      /**
       * Is Stale
       * @description True when the transcript changed after generation — drives the Outdated badge in the UI.
       */
      is_stale: boolean
      /** Keywords */
      keywords: string[]
      /** Meeting Id */
      meeting_id: number
      /** Model */
      model?: string | null
      /** Notes */
      notes: components['schemas']['NoteGroup'][]
      /** Outline */
      outline: components['schemas']['OutlineEntry'][]
      /** Overview */
      overview?: string | null
      /**
       * Provider
       * @description Which provider produced this. Surfaced in the UI.
       */
      provider: string
    }
    /** TagRef */
    TagRef: {
      /** Color */
      color: string
      /** Id */
      id: number
      /** Name */
      name: string
    }
    /**
     * TeamMemberOut
     * @description A row of the Team page's members table (T-30.4).
     *
     *     No email — `UserOut` establishes that email is only ever returned for the
     *     current user, and a placeholder page is not a reason to widen that.
     *     `role` is presentation-only until real auth exists: the seeded default
     *     user reads as the workspace admin, everyone else as a member.
     */
    TeamMemberOut: {
      /** Avatar Url */
      avatar_url?: string | null
      /** Id */
      id: number
      /** Meetings Hosted */
      meetings_hosted: number
      /** Name */
      name: string
      /**
       * Role
       * @description 'Admin' for the seeded default user, else 'Member'.
       */
      role: string
    }
    /**
     * TranscriptHit
     * @description A transcript line that matched, with enough context to be worth showing.
     */
    TranscriptHit: {
      /** Matches */
      matches: components['schemas']['MatchRange'][]
      /** Meeting Id */
      meeting_id: number
      /** Meeting Title */
      meeting_title: string
      /** Segment Id */
      segment_id: number
      /** Snippet */
      snippet: string
      /** Speaker */
      speaker: string
      /** Start Ms */
      start_ms: number
    }
    /**
     * TranscriptPage
     * @description A page of segments plus everything needed to render them.
     *
     *     `speakers` is a per-page dictionary rather than a field on each segment:
     *     a page of 200 segments typically has three or four distinct speakers, so
     *     inlining them repeats the same label and colour ~50 times each.
     */
    TranscriptPage: {
      /** Next Cursor */
      next_cursor?: number | null
      /** Segments */
      segments: components['schemas']['SegmentOut'][]
      /** Speakers */
      speakers: components['schemas']['SpeakerRef'][]
      /** Total */
      total: number
    }
    /**
     * TranscriptPreview
     * @description What the parser found, before anything is created (T-26.7).
     */
    TranscriptPreview: {
      /** Duration Ms */
      duration_ms: number
      /** Participants */
      participants: string[]
      /** Segments */
      segments: components['schemas']['ImportedSegment'][]
      /** Speakers */
      speakers: string[]
      /** Strategy */
      strategy: string
      /** Title */
      title: string | null
    }
    /**
     * UserOut
     * @description The signed-in user's own record, from `/me`.
     */
    UserOut: {
      /** Avatar Url */
      avatar_url?: string | null
      /**
       * Email
       * @description Only ever returned for the current user.
       */
      email: string
      /** Id */
      id: number
      /** Name */
      name: string
    }
    /**
     * UserRef
     * @description The minimum needed to render an avatar and a name.
     *
     *     Deliberately not the full user record: this is embedded in every meeting
     *     row, so anything added here is paid for 20 times per page.
     */
    UserRef: {
      /** Avatar Url */
      avatar_url?: string | null
      /** Id */
      id: number
      /** Name */
      name: string
    }
    /** ValidationError */
    ValidationError: {
      /** Context */
      ctx?: Record<string, never>
      /** Input */
      input?: unknown
      /** Location */
      loc: (string | number)[]
      /** Message */
      msg: string
      /** Error Type */
      type: string
    }
    /**
     * Visibility
     * @enum {string}
     */
    Visibility: 'private' | 'team' | 'public'
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  health_api_health_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HealthResponse']
        }
      }
      /** @description Unexpected error. `details.request_id` correlates to logs. */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description A dependency is unavailable. */
      503: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  list_channels_api_v1_channels_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SidebarChannels']
        }
      }
      /** @description Unexpected error. `details.request_id` correlates to logs. */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  read_me_api_v1_me_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['UserOut']
        }
      }
      /** @description Unexpected error. `details.request_id` correlates to logs. */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description A dependency is unavailable. */
      503: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  list_meetings_api_v1_meetings_get: {
    parameters: {
      query?: {
        /** @description Free text across title, overview, people and transcript. */
        q?: string | null
        /** @description Host name, partial match. */
        host?: string | null
        /** @description Participant name, partial match. */
        participant?: string | null
        /** @description Inclusive start date (UTC). */
        from?: string | null
        /** @description Inclusive END date (UTC). */
        to?: string | null
        /** @description Seconds. */
        min_duration?: number | null
        /** @description Seconds. */
        max_duration?: number | null
        /** @description Tag names. ALL must match. */
        tags?: string[] | null
        /** @description Channel slug. */
        channel?: string | null
        /** @description True = has OPEN action items. */
        has_action_items?: boolean | null
        /** @description How it was captured. */
        source?: components['schemas']['MeetingSource'] | null
        /** @description One of: -created_at, -duration_seconds, -started_at, -title, created_at, duration_seconds, started_at, title */
        sort?: string
        /** @description 1-indexed page number. */
        page?: number
        /** @description Items per page. Clamped to 100. */
        page_size?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Page_MeetingListItem_']
        }
      }
      /** @description Invalid payload; `details` is keyed by field path. */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unexpected error. `details.request_id` correlates to logs. */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  create_meeting_api_v1_meetings_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['MeetingCreate']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MeetingDetail']
        }
      }
      /** @description Invalid payload; `details` is keyed by field path. */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unexpected error. `details.request_id` correlates to logs. */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  delete_action_item_api_v1_meetings_action_items__item_id__delete: {
    parameters: {
      query?: never
      header?: never
      path: {
        item_id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ActionItemOut']
        }
      }
      /** @description No meeting with this id. */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Deleted, but restorable. */
      410: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
      /** @description Unexpected error. `details.request_id` correlates to logs. */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  update_action_item_api_v1_meetings_action_items__item_id__patch: {
    parameters: {
      query?: never
      header?: never
      path: {
        item_id: number
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ActionItemUpdate']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ActionItemOut']
        }
      }
      /** @description No meeting with this id. */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Deleted, but restorable. */
      410: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Invalid payload; `details` is keyed by field path. */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unexpected error. `details.request_id` correlates to logs. */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  bulk_delete_api_v1_meetings_bulk_delete_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['BulkDeleteRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BulkDeleteResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
      /** @description Unexpected error. `details.request_id` correlates to logs. */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  bulk_restore_api_v1_meetings_bulk_restore_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['BulkDeleteRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BulkRestoreResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
      /** @description Unexpected error. `details.request_id` correlates to logs. */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  meeting_facets_api_v1_meetings_facets_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Facets']
        }
      }
      /** @description Unexpected error. `details.request_id` correlates to logs. */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  import_meeting_api_v1_meetings_import_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['MeetingImport']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MeetingDetail']
        }
      }
      /** @description Invalid payload; `details` is keyed by field path. */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unexpected error. `details.request_id` correlates to logs. */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  parse_transcript_preview_api_v1_meetings_parse_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: {
      content: {
        'multipart/form-data': components['schemas']['Body_parse_transcript_preview_api_v1_meetings_parse_post']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TranscriptPreview']
        }
      }
      /** @description Invalid payload; `details` is keyed by field path. */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unexpected error. `details.request_id` correlates to logs. */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  update_segment_api_v1_meetings_segments__segment_id__patch: {
    parameters: {
      query?: never
      header?: never
      path: {
        segment_id: number
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['SegmentUpdate']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SegmentOut']
        }
      }
      /** @description No meeting with this id. */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Deleted, but restorable. */
      410: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Invalid payload; `details` is keyed by field path. */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unexpected error. `details.request_id` correlates to logs. */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  update_speaker_api_v1_meetings_speakers__speaker_id__patch: {
    parameters: {
      query?: never
      header?: never
      path: {
        speaker_id: number
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['SpeakerUpdate']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SpeakerRef']
        }
      }
      /** @description No meeting with this id. */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Deleted, but restorable. */
      410: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Invalid payload; `details` is keyed by field path. */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unexpected error. `details.request_id` correlates to logs. */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  get_meeting_api_v1_meetings__meeting_id__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        meeting_id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MeetingDetail']
        }
      }
      /** @description No meeting with this id. */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Deleted, but restorable. */
      410: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
      /** @description Unexpected error. `details.request_id` correlates to logs. */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  delete_meeting_api_v1_meetings__meeting_id__delete: {
    parameters: {
      query?: never
      header?: never
      path: {
        meeting_id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description No meeting with this id. */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Deleted, but restorable. */
      410: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
      /** @description Unexpected error. `details.request_id` correlates to logs. */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  update_meeting_api_v1_meetings__meeting_id__patch: {
    parameters: {
      query?: never
      header?: never
      path: {
        meeting_id: number
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['MeetingUpdate']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MeetingDetail']
        }
      }
      /** @description No meeting with this id. */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Deleted, but restorable. */
      410: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Invalid payload; `details` is keyed by field path. */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unexpected error. `details.request_id` correlates to logs. */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  list_action_items_api_v1_meetings__meeting_id__action_items_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        meeting_id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ActionItemOut'][]
        }
      }
      /** @description No meeting with this id. */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Deleted, but restorable. */
      410: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
      /** @description Unexpected error. `details.request_id` correlates to logs. */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  create_action_item_api_v1_meetings__meeting_id__action_items_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        meeting_id: number
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ActionItemCreate']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ActionItemOut']
        }
      }
      /** @description No meeting with this id. */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Deleted, but restorable. */
      410: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Invalid payload; `details` is keyed by field path. */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unexpected error. `details.request_id` correlates to logs. */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  get_media_api_v1_meetings__meeting_id__media_get: {
    parameters: {
      query?: never
      header?: {
        Range?: string | null
      }
      path: {
        meeting_id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description No meeting with this id. */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Deleted, but restorable. */
      410: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
      /** @description Unexpected error. `details.request_id` correlates to logs. */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  restore_meeting_api_v1_meetings__meeting_id__restore_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        meeting_id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MeetingDetail']
        }
      }
      /** @description No meeting with this id. */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Deleted, but restorable. */
      410: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
      /** @description Unexpected error. `details.request_id` correlates to logs. */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  get_speakers_api_v1_meetings__meeting_id__speakers_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        meeting_id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SpeakerRef'][]
        }
      }
      /** @description No meeting with this id. */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Deleted, but restorable. */
      410: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
      /** @description Unexpected error. `details.request_id` correlates to logs. */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  create_speaker_api_v1_meetings__meeting_id__speakers_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        meeting_id: number
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['SpeakerCreate']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SpeakerRef']
        }
      }
      /** @description No meeting with this id. */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Deleted, but restorable. */
      410: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Invalid payload; `details` is keyed by field path. */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unexpected error. `details.request_id` correlates to logs. */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  get_summary_api_v1_meetings__meeting_id__summary_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        meeting_id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SummaryOut']
        }
      }
      /** @description No meeting with this id. */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Deleted, but restorable. */
      410: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
      /** @description Unexpected error. `details.request_id` correlates to logs. */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  regenerate_summary_api_v1_meetings__meeting_id__summary_regenerate_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        meeting_id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SummaryOut']
        }
      }
      /** @description No meeting with this id. */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Deleted, but restorable. */
      410: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
      /** @description Rate limit exceeded. */
      429: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unexpected error. `details.request_id` correlates to logs. */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  get_transcript_api_v1_meetings__meeting_id__transcript_get: {
    parameters: {
      query?: {
        /** @description `sequence` of the last segment seen. */
        cursor?: number | null
        limit?: number
        /** @description Filter to matching segments. */
        q?: string | null
      }
      header?: never
      path: {
        meeting_id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TranscriptPage']
        }
      }
      /** @description No meeting with this id. */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Deleted, but restorable. */
      410: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
      /** @description Unexpected error. `details.request_id` correlates to logs. */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  search_api_v1_search_get: {
    parameters: {
      query: {
        /** @description Search term. Treated literally, not as a pattern. */
        q: string
        /** @description Max hits per group. */
        limit?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SearchResults']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
      /** @description Unexpected error. `details.request_id` correlates to logs. */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  list_users_api_v1_users_get: {
    parameters: {
      query?: {
        /** @description 1-indexed page number. */
        page?: number
        /** @description Items per page. Clamped to 100. */
        page_size?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Page_TeamMemberOut_']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
      /** @description Unexpected error. `details.request_id` correlates to logs. */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
}
