"""comment mentions and edited marker

Revision ID: 0fcabb502322
Revises: 390a23c1d7f6
Create Date: 2026-07-27

Two additions for T-31: the `comment_mentions` association table (who a
comment @mentions is queryable data, not styled text — T-31.4) and
`comments.edited_at` (the `edited` marker tracks body changes only, because
`updated_at` also moves on resolve/unresolve — T-31.7). Autogenerated and
reviewed; nothing else changes.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0fcabb502322"
down_revision: str | Sequence[str] | None = "390a23c1d7f6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Create comment_mentions; add comments.edited_at."""
    op.create_table(
        "comment_mentions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("comment_id", sa.Integer(), nullable=False),
        sa.Column("participant_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["comment_id"],
            ["comments.id"],
            name=op.f("fk_comment_mentions_comment_id_comments"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["participant_id"],
            ["participants.id"],
            name=op.f("fk_comment_mentions_participant_id_participants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_comment_mentions")),
        sa.UniqueConstraint("comment_id", "participant_id", name="uq_comment_mentions"),
    )
    with op.batch_alter_table("comment_mentions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_comment_mentions_comment_id"), ["comment_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_comment_mentions_participant_id"), ["participant_id"], unique=False
        )

    with op.batch_alter_table("comments", schema=None) as batch_op:
        batch_op.add_column(sa.Column("edited_at", sa.DateTime(timezone=True), nullable=True))


def downgrade() -> None:
    """Drop both."""
    with op.batch_alter_table("comments", schema=None) as batch_op:
        batch_op.drop_column("edited_at")

    with op.batch_alter_table("comment_mentions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_comment_mentions_participant_id"))
        batch_op.drop_index(batch_op.f("ix_comment_mentions_comment_id"))

    op.drop_table("comment_mentions")
