"""initial schema

Revision ID: 7166b3ec3ab0
Revises:
Create Date: 2026-07-26 20:23:28.227727

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7166b3ec3ab0"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "channels",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("slug", sa.String(length=80), nullable=False),
        sa.Column("is_private", sa.Boolean(), nullable=False),
        sa.Column("icon", sa.String(length=40), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_channels")),
        sa.UniqueConstraint("slug", name="uq_channels_slug"),
    )
    op.create_table(
        "tags",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=24), nullable=False),
        sa.Column("color", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tags")),
        sa.UniqueConstraint("name", name="uq_tags_name"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("avatar_url", sa.String(length=500), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=True)

    op.create_table(
        "meetings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("duration_seconds", sa.Integer(), nullable=False),
        sa.Column("host_id", sa.Integer(), nullable=False),
        sa.Column("channel_id", sa.Integer(), nullable=True),
        sa.Column("media_url", sa.String(length=500), nullable=True),
        sa.Column(
            "media_type",
            sa.Enum("audio", "video", "none", name="media_type", native_enum=False),
            nullable=False,
        ),
        sa.Column("language", sa.String(length=10), nullable=False),
        sa.Column(
            "source",
            sa.Enum(
                "upload", "manual", "seed", "integration", name="meeting_source", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column(
            "visibility",
            sa.Enum("private", "team", "public", name="visibility", native_enum=False),
            nullable=False,
        ),
        sa.Column(
            "processing_status",
            sa.Enum(
                "pending",
                "processing",
                "ready",
                "failed",
                name="processing_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("seed_key", sa.String(length=80), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["channel_id"],
            ["channels.id"],
            name=op.f("fk_meetings_channel_id_channels"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["host_id"], ["users.id"], name=op.f("fk_meetings_host_id_users"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_meetings")),
        sa.UniqueConstraint("seed_key", name=op.f("uq_meetings_seed_key")),
    )
    with op.batch_alter_table("meetings", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_meetings_channel_id"), ["channel_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_meetings_deleted_at"), ["deleted_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_meetings_host_id"), ["host_id"], unique=False)
        batch_op.create_index("ix_meetings_started_at", ["started_at"], unique=False)

    op.create_table(
        "keywords",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("meeting_id", sa.Integer(), nullable=False),
        sa.Column("term", sa.String(length=80), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["meeting_id"],
            ["meetings.id"],
            name=op.f("fk_keywords_meeting_id_meetings"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_keywords")),
        sa.UniqueConstraint("meeting_id", "term", name="uq_keywords_meeting_term"),
    )
    with op.batch_alter_table("keywords", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_keywords_meeting_id"), ["meeting_id"], unique=False)

    op.create_table(
        "meeting_tags",
        sa.Column("meeting_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["meeting_id"],
            ["meetings.id"],
            name=op.f("fk_meeting_tags_meeting_id_meetings"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"], ["tags.id"], name=op.f("fk_meeting_tags_tag_id_tags"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("meeting_id", "tag_id", name=op.f("pk_meeting_tags")),
    )
    op.create_table(
        "participants",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("meeting_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("display_name", sa.String(length=120), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column(
            "role",
            sa.Enum("host", "attendee", "invited", name="participant_role", native_enum=False),
            nullable=False,
        ),
        sa.Column("attended", sa.Boolean(), nullable=False),
        sa.Column("talk_seconds", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["meeting_id"],
            ["meetings.id"],
            name=op.f("fk_participants_meeting_id_meetings"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_participants_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_participants")),
        sa.UniqueConstraint("meeting_id", "display_name", name="uq_participants_meeting_name"),
    )
    with op.batch_alter_table("participants", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_participants_meeting_id"), ["meeting_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_participants_user_id"), ["user_id"], unique=False)

    op.create_table(
        "soundbites",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("meeting_id", sa.Integer(), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("start_ms", sa.Integer(), nullable=False),
        sa.Column("end_ms", sa.Integer(), nullable=False),
        sa.Column("auto_generated", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "end_ms - start_ms <= 180000", name=op.f("ck_soundbites_soundbite_max_length")
        ),
        sa.CheckConstraint(
            "end_ms - start_ms >= 3000", name=op.f("ck_soundbites_soundbite_min_length")
        ),
        sa.CheckConstraint(
            "end_ms > start_ms", name=op.f("ck_soundbites_soundbite_range_non_empty")
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_soundbites_created_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["meeting_id"],
            ["meetings.id"],
            name=op.f("fk_soundbites_meeting_id_meetings"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_soundbites")),
    )
    with op.batch_alter_table("soundbites", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_soundbites_meeting_id"), ["meeting_id"], unique=False)

    op.create_table(
        "summaries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("meeting_id", sa.Integer(), nullable=False),
        sa.Column("overview", sa.Text(), nullable=True),
        sa.Column("gist", sa.String(length=400), nullable=True),
        sa.Column("provider", sa.String(length=60), nullable=False),
        sa.Column("model", sa.String(length=120), nullable=True),
        sa.Column(
            "generated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("is_stale", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["meeting_id"],
            ["meetings.id"],
            name=op.f("fk_summaries_meeting_id_meetings"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_summaries")),
    )
    with op.batch_alter_table("summaries", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_summaries_meeting_id"), ["meeting_id"], unique=True)

    op.create_table(
        "action_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("meeting_id", sa.Integer(), nullable=False),
        sa.Column("assignee_participant_id", sa.Integer(), nullable=True),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("open", "completed", name="action_item_status", native_enum=False),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "source",
            sa.Enum("ai", "manual", name="action_item_source", native_enum=False),
            nullable=False,
        ),
        sa.Column("start_ms", sa.Integer(), nullable=True),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["assignee_participant_id"],
            ["participants.id"],
            name=op.f("fk_action_items_assignee_participant_id_participants"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["meeting_id"],
            ["meetings.id"],
            name=op.f("fk_action_items_meeting_id_meetings"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_action_items")),
    )
    with op.batch_alter_table("action_items", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_action_items_assignee_participant_id"),
            ["assignee_participant_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_action_items_meeting_id"), ["meeting_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_action_items_status"), ["status"], unique=False)

    op.create_table(
        "speakers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("meeting_id", sa.Integer(), nullable=False),
        sa.Column("participant_id", sa.Integer(), nullable=True),
        sa.Column("label", sa.String(length=120), nullable=False),
        sa.Column("color_index", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["meeting_id"],
            ["meetings.id"],
            name=op.f("fk_speakers_meeting_id_meetings"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["participant_id"],
            ["participants.id"],
            name=op.f("fk_speakers_participant_id_participants"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_speakers")),
        sa.UniqueConstraint("meeting_id", "label", name="uq_speakers_meeting_label"),
    )
    with op.batch_alter_table("speakers", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_speakers_meeting_id"), ["meeting_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_speakers_participant_id"), ["participant_id"], unique=False
        )

    op.create_table(
        "summary_sections",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("summary_id", sa.Integer(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("outline", "notes", name="summary_section_kind", native_enum=False),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=300), nullable=True),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("start_ms", sa.Integer(), nullable=True),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["summary_id"],
            ["summaries.id"],
            name=op.f("fk_summary_sections_summary_id_summaries"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_summary_sections")),
    )
    with op.batch_alter_table("summary_sections", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_summary_sections_summary_id"), ["summary_id"], unique=False
        )

    op.create_table(
        "transcript_segments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("meeting_id", sa.Integer(), nullable=False),
        sa.Column("speaker_id", sa.Integer(), nullable=False),
        sa.Column("start_ms", sa.Integer(), nullable=False),
        sa.Column("end_ms", sa.Integer(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("is_edited", sa.Boolean(), nullable=False),
        sa.Column("original_text", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "end_ms >= start_ms", name=op.f("ck_transcript_segments_segment_end_after_start")
        ),
        sa.CheckConstraint(
            "start_ms >= 0", name=op.f("ck_transcript_segments_segment_start_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["meeting_id"],
            ["meetings.id"],
            name=op.f("fk_transcript_segments_meeting_id_meetings"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["speaker_id"],
            ["speakers.id"],
            name=op.f("fk_transcript_segments_speaker_id_speakers"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_transcript_segments")),
        sa.UniqueConstraint("meeting_id", "sequence", name="uq_segments_meeting_sequence"),
    )
    with op.batch_alter_table("transcript_segments", schema=None) as batch_op:
        batch_op.create_index("ix_segments_meeting_start", ["meeting_id", "start_ms"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_transcript_segments_meeting_id"), ["meeting_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_transcript_segments_speaker_id"), ["speaker_id"], unique=False
        )

    op.create_table(
        "bookmarks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("meeting_id", sa.Integer(), nullable=False),
        sa.Column("segment_id", sa.Integer(), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_bookmarks_created_by_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["meeting_id"],
            ["meetings.id"],
            name=op.f("fk_bookmarks_meeting_id_meetings"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["segment_id"],
            ["transcript_segments.id"],
            name=op.f("fk_bookmarks_segment_id_transcript_segments"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bookmarks")),
        sa.UniqueConstraint("segment_id", "created_by", name="uq_bookmarks_segment_user"),
    )
    with op.batch_alter_table("bookmarks", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_bookmarks_meeting_id"), ["meeting_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_bookmarks_segment_id"), ["segment_id"], unique=False)

    op.create_table(
        "comments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("meeting_id", sa.Integer(), nullable=False),
        sa.Column("segment_id", sa.Integer(), nullable=True),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("start_ms", sa.Integer(), nullable=True),
        sa.Column("is_resolved", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["users.id"],
            name=op.f("fk_comments_author_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["meeting_id"],
            ["meetings.id"],
            name=op.f("fk_comments_meeting_id_meetings"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["comments.id"],
            name=op.f("fk_comments_parent_id_comments"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["segment_id"],
            ["transcript_segments.id"],
            name=op.f("fk_comments_segment_id_transcript_segments"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_comments")),
    )
    with op.batch_alter_table("comments", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_comments_author_id"), ["author_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_comments_deleted_at"), ["deleted_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_comments_meeting_id"), ["meeting_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_comments_parent_id"), ["parent_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_comments_segment_id"), ["segment_id"], unique=False)

    op.create_table(
        "highlights",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("meeting_id", sa.Integer(), nullable=False),
        sa.Column("segment_id", sa.Integer(), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.Column("start_offset", sa.Integer(), nullable=False),
        sa.Column("end_offset", sa.Integer(), nullable=False),
        sa.Column(
            "color",
            sa.Enum("amber", "green", "blue", "pink", name="highlight_color", native_enum=False),
            nullable=False,
        ),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "end_offset > start_offset", name=op.f("ck_highlights_highlight_range_non_empty")
        ),
        sa.CheckConstraint(
            "start_offset >= 0", name=op.f("ck_highlights_highlight_start_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_highlights_created_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["meeting_id"],
            ["meetings.id"],
            name=op.f("fk_highlights_meeting_id_meetings"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["segment_id"],
            ["transcript_segments.id"],
            name=op.f("fk_highlights_segment_id_transcript_segments"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_highlights")),
    )
    with op.batch_alter_table("highlights", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_highlights_meeting_id"), ["meeting_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_highlights_segment_id"), ["segment_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("highlights", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_highlights_segment_id"))
        batch_op.drop_index(batch_op.f("ix_highlights_meeting_id"))

    op.drop_table("highlights")
    with op.batch_alter_table("comments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_comments_segment_id"))
        batch_op.drop_index(batch_op.f("ix_comments_parent_id"))
        batch_op.drop_index(batch_op.f("ix_comments_meeting_id"))
        batch_op.drop_index(batch_op.f("ix_comments_deleted_at"))
        batch_op.drop_index(batch_op.f("ix_comments_author_id"))

    op.drop_table("comments")
    with op.batch_alter_table("bookmarks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_bookmarks_segment_id"))
        batch_op.drop_index(batch_op.f("ix_bookmarks_meeting_id"))

    op.drop_table("bookmarks")
    with op.batch_alter_table("transcript_segments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_transcript_segments_speaker_id"))
        batch_op.drop_index(batch_op.f("ix_transcript_segments_meeting_id"))
        batch_op.drop_index("ix_segments_meeting_start")

    op.drop_table("transcript_segments")
    with op.batch_alter_table("summary_sections", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_summary_sections_summary_id"))

    op.drop_table("summary_sections")
    with op.batch_alter_table("speakers", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_speakers_participant_id"))
        batch_op.drop_index(batch_op.f("ix_speakers_meeting_id"))

    op.drop_table("speakers")
    with op.batch_alter_table("action_items", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_action_items_status"))
        batch_op.drop_index(batch_op.f("ix_action_items_meeting_id"))
        batch_op.drop_index(batch_op.f("ix_action_items_assignee_participant_id"))

    op.drop_table("action_items")
    with op.batch_alter_table("summaries", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_summaries_meeting_id"))

    op.drop_table("summaries")
    with op.batch_alter_table("soundbites", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_soundbites_meeting_id"))

    op.drop_table("soundbites")
    with op.batch_alter_table("participants", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_participants_user_id"))
        batch_op.drop_index(batch_op.f("ix_participants_meeting_id"))

    op.drop_table("participants")
    op.drop_table("meeting_tags")
    with op.batch_alter_table("keywords", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_keywords_meeting_id"))

    op.drop_table("keywords")
    with op.batch_alter_table("meetings", schema=None) as batch_op:
        batch_op.drop_index("ix_meetings_started_at")
        batch_op.drop_index(batch_op.f("ix_meetings_host_id"))
        batch_op.drop_index(batch_op.f("ix_meetings_deleted_at"))
        batch_op.drop_index(batch_op.f("ix_meetings_channel_id"))

    op.drop_table("meetings")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_email"))

    op.drop_table("users")
    op.drop_table("tags")
    op.drop_table("channels")
    # ### end Alembic commands ###
